### PR TITLE
Added inScope static

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by rubys** [comment]
I have some minor editorial comments (for example: same origin needs to be spelled out more clearly; and initially it would be based on the definition of [origin](https://specs.webplatform.org/url/webspecs/develop/#origin) in this specification).  I can take a pass at making these changes, and follow up comments and/or pull requests could be used for further refinements.

If something like [CORS](https://fetch.spec.whatwg.org/#http-cors-protocol) is desired, that could also be pursued in a separate issue/pull request.

Given that @annevk has pushed back on the need for this API, can we get a second browser vendor to step forward and express an intent to implement this?

**Comment by marcoscaceres** [comment]
On Friday, December 26, 2014, Sam Ruby notifications@github.com wrote:

> I have some minor editorial comments (for example: same origin needs to be
> spelled out more clearly; and initially it would be based on the definition
> of origin https://specs.webplatform.org/url/webspecs/develop/#origin in
> this specification. I can take a pass at making these changes, and follow
> up comments and/or pull requests could be used for further refinements.

Sounds good. Thanks for offering to help!

**Comment by rubys** [comment]
> I'm not sure what you mean here? Why would CORS come into play when comparing URLs?

I'm just trying to be thorough.  Ruling out CORS makes things simpler, so that's good.  Now lets be thorough from the other direction: I'll note that this isn't a byte-for-byte comparison, but rather a comparison of the values of individual URL components _after parsing_.  At the moment, there is still quite a bit of [variety](https://url.spec.whatwg.org/interop/test-results/) as to how user agents parse URLs.  At a minimum, this merits a cautionary note.  A more aggressive stance would be to return false for all [non-conforming](https://specs.webplatform.org/url/webspecs/develop/#url-writing) inputs.  That's still not perfect, but adding more conformance checks may be easier to get consensus on than to get implementation movement towards interop on non-conforming inputs.  It is also easier to lift a restriction later than it would be to add one.

> Probably need to move this to a larger forum once a concrete proposal is ready. I'm happy to do that once the PR is ready.

I thought this was a concrete proposal.  I'm willing to merge it, and then make editorial changes on top of it.  The one thing I'm holding on is either an indication that @annevk doesn't object, or an indication that browser vendors will implement this anyway.

**Comment by marcoscaceres** [comment]
Talked to Anne briefly - will define what I need in my own spec. We can move this stuff down the stack to the URL layer if/when developers require it.

**Pull request closed without merging**
